import "./arrow-right.svg";
import "./double-arrow-right.svg";
import "./file.svg";
import "./inventory.svg";
import "./javatpoint-logo.svg";
import "./key.svg";
import "./opened-folder.svg";
import "./package.svg";
import "./tutorialspoint-logo.svg";